#!/usr/bin/env bash
# Bash script that configres  a new Ubuntu machine
# Install and configure Nginx

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
