#!/usr/bin/env bash
# Bash script to install Nginx and configure a 301 redirect

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/@fransixpaul permanent;' /ect/nginx/sites-available/default
service nginx restart
