#!/usr/bin/env bash
# Modify the Nginx configuration to run as the nginx user
# Change the listening port to 8080

if ! command -v nginx > /dev/null; then
	apt-get update
	apt-get install -y nginx
fi

sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

sed -i \
's/listen 80 default_server;/listen 8080 default_server;/' \
/etc/nginx/sites-available/default

sed -i \
's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/' \
/etc/nginx/sites-available/default


if ! id -u nginx > /dev/null 2>&1; then
	adduser \
	--system \
	--no-create-home \
	--shell /bin/false \
	--group \
	--disabled-login \
	nginx
fi

sudo systemctl restart nginx

pgrep -af nginx
